#!/bin/bash

declare $(cat version.h | awk '{print $2"="$3}')
VERSION="2020.2.$APPVERSION-beta"

if [[ "$DOCKERFILE_PATH" == *.arm32v7 ]];
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION-arm32v7
    docker push $DOCKER_REPO:$VERSION-arm32v7
fi

if [[ "$DOCKERFILE_PATH" == *.arm64v8 ]];
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION-arm64v8
    docker push $DOCKER_REPO:$VERSION-arm64v8
fi

if [[ "$DOCKERFILE_PATH" == *.x86-64 ]];
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION-x86-64
    docker push $DOCKER_REPO:$VERSION-x86-64
fi

docker pull toussii/domoticz:latest-x86-64
docker pull toussii/domoticz:latest-arm32v7
docker pull toussii/domoticz:latest-arm64v8

docker manifest create \
toussii/domoticz:latest \
--amend toussii/domoticz:latest-x86-64 \
--amend toussii/domoticz:latest-arm32v7 \
--amend toussii/domoticz:latest-arm64v8

docker manifest push toussii/domoticz:latest
